### ISSUE TITLE
Even with "draft: false", drafts get made

### ISSUE THREAD

**Issue by probonopd** [softprops/action-gh-release#379]
I am using this:

```
    - name: Upload Artifacts to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/attrutil
        tag_name: continuous
        target_commitish: ${{ github.sha }}
        draft: false
```

https://github.com/probonopd/attrutil/blob/main/.github/workflows/build.yml

I was hoping that thanks to `draft: false`, the releases would not be created as drafts, but they are.

**Comment by boozook** [comment]
I suppose that there's Github's "boo is not bool"-problem. Try to use strings like 'false' 
or if you really need `bool` - pass empty string `""` or `${{ null }}`, so it casts to boolean as `false`.

**Comment by probonopd** [comment]
Thanks @boozook. Is this a change @softprops would need to make in this action, or should it work if I simply set `draft: ${{ null }}` instead of `draft: false`?

**Comment by boozook** [comment]
@probonopd, looking at [that line][line] I suppose the value is interpreting as following:
- `true` if value == `"true"` (string)
- `false` (actually `undefined`, sic!) for any other value.

Also [there][inputs] input is defined as empty by default.

So in this case for `false` I could try `${{ null }}` or empty string as by default.

_Anyway, it's just my suppose, I'm not sure and I'm not a guru of this language._

[inputs]: https://github.com/softprops/action-gh-release/blob/master/action.yml#L18-L20
[line]: https://github.com/softprops/action-gh-release/blob/master/src/util.ts#L63

**Comment by PredatorCZ** [comment]
I've had the same issue. I am using the same workflow (remove tag + release, then release again).
`draft` is false by default, so there is no need to explicitly specify it.
I've fixed this issue by putting sleep between deletion and release steps. (In your example on this line: https://github.com/probonopd/attrutil/blob/a87a383bcd9061fee192208572de9fae3a141e8b/.github/workflows/build.yml#L37)

Very simple code:

```yaml
    - name: Wait a sec
      run: sleep 2
```

Sleep variable should be tweaked

The reasoning for sleep is, that GH API is slower then action script, so by the time CI is releasing, deletion is still queued on gh side. But that is just a silly theory of mine.

**Comment by probonopd** [comment]
Still doesn't seem to work:

https://github.com/probonopd/attrutil/releases

**Comment by PredatorCZ** [comment]
I'm also using `delete-tag-and-release` action instead of git command to remove previous releases.
Or/and increase wait time, 2s delay is working for me, that doesn't mean it's the rule.

**Comment by chenrui333** [comment]
I could not reproduce or isolate this on current master and the latest 2.5.2 release in the current regression sweep, so I am closing it to keep the backlog focused on confirmed current bugs. If you are still seeing a different current failure, please open a new issue with a minimal repro or sanitized workflow snippet and the failing logs.
